### ISSUE TITLE
memory issues with `hetkmers.py`

### ISSUE THREAD

**Issue by KamilSJaron** [tbenavi1/sibling_kmers#2]
I run `hetkmers.py` on 1.3G genome, cca 30x.

The script allocated 750Gbp of memory at the point of generating the graph G. I killed the process in this moment.

The graph is very efficient implementation in terms on number of lines, but it does not scale well for bigger genomes. The computation was long, but not super long (2 days for the calculation of pairs distant exactly 1). Speeding up would be useful, but not necessary, the memory is issue here.

Any ideas @tbenavi1 ?

**Comment by tbenavi1** [comment]
Fixed with b49d6bf939a821a07174eb13bb1285e00e154656. The code now converts kmers to ints as it loads, dramatically reducing the memory. It no longer requires pandas or networkx. It also uses multiple processes to speed up the analysis.
