### ISSUE TITLE
Replacement of Jellyfish

### ISSUE THREAD

**Issue by KamilSJaron** [tbenavi1/sibling_kmers#4]
I have been told that there is 10x faster alternative of Jellyfish. Even Jellyfish is not the bottleneck now, it might be useful to switch to something faster:

https://academic.oup.com/bioinformatics/article/31/10/1569/177467

their web is down, but it seems that the project have migrated to GitHub https://github.com/refresh-bio/KMC

**Comment by tbenavi1** [comment]
I have edited README.md to explain the usage of KMC.

**Comment by KamilSJaron** [comment]
Just for a record: https://github.com/lh3/yak there might be a new player in the game.
