### ISSUE TITLE
Unexpected Polyploidy

### ISSUE THREAD

**Issue by jhcaddisfly** [tbenavi1/sibling_kmers#92]
I have troubles understanding my smudgeplots for two individuals of the same species. 
I have used v0.2.3 and the following command to generate the plots:

```
I first extracted genomic kmers using coverage thresholds which were estimated from the kmer histograms generated by jellyfish with the internal smudgeplot script smudgeplot.py as follows: 
* = ind1 / ind2
L=$(smudgeplot.py cutoff *_k21.hist L)
U=$(smudgeplot.py cutoff *_k21.hist U)
These were 21 (individual 1) / 23 (individual 2) and 690 (individual 1) / 790 (individual 2).
Then, I extracted kmers in the coverage range from L to U  using jellyfish dump -c -L 41 -U 2400 *_kmer_counts.jf -o *_jfkmers
I then used smudgeplot.py hetkmers -o * *_jfkmers to compute the set of kmers and 
smudgeplot.py plot -i *_kmer_pairs_coverages.tsv -o * to plot these.
```

and it look like this:

Now, I have indication already of genome size from genomescope and flow cytometry (651.30 Mbp but a different individual of the same species).
The Genomescope results look like this:

http://qb.cshl.edu/genomescope/genomescope2.0/analysis.php?code=b7yzvd5lbmeuMEEx5swf

http://qb.cshl.edu/genomescope/genomescope2.0/analysis.php?code=e68aubTXZEgN9Ix2u9td

![ind2_smudgeplot_log10](https://user-images.githubusercontent.com/55246900/137378471-75adb380-dc1c-46ef-8d6f-d1c2c9a2300e.png)
![ind2_smudgeplot](https://user-images.githubusercontent.com/55246900/137378472-7e580076-cbde-4207-a199-426868fcc3c2.png)
![ind1_smudgeplot_log10](https://user-images.githubusercontent.com/55246900/137378476-48541aa6-e206-47d2-baeb-363dd6262ed2.png)
![ind1_smudgeplot](https://user-images.githubusercontent.com/55246900/137378477-31f1c561-5e66-46e4-a20f-531d8dbcabd5.png)
This does not make sense together with the smudge because it predicts unexpected ploidy.

How should I understand my smudgeplot?

Thanks,
J.

**Comment by KamilSJaron** [comment]
Hello J.,

not sure what's the question here. I presume that you have a diploid predicted to be a tetraploid.

What what I can tell, there is only very little heterozygosity in the species (looking at the genomescope estimates). Perhaps it's the same problem as in the diploid strawberry case which also looked tetraploid because the paralogy signal dominated the smudgeplot due to very low heterozygosity: https://github.com/KamilSJaron/smudgeplot/wiki/tutorial-strawberry

**Comment by jhcaddisfly** [comment]
Hello,

Thank you very much for your quick response!
Yes, my question was why smudgeplot predicts my studied organism to be tetraploid since I would expect it to be diploid because of the haploid genome size estimate from FCM and Genomscope2. 
To conclude, can I argue that because of the low heterozygosity (0.35-0.39%) the duplication signal is relatively stronger than the heterozygosity signal)? So, are the duplications rather recent?  Can I say that my organisms have a lot of closely related paralogs
(paralogs: AABB 81% / 69% vs. heterozygous loci: AB 19% / 17%) and that this is cause because smugeplot picks two homozygous loci that are exactly one nucleotide different up as AABB?  
So, do you think the evidence for tetraploidy according to smudgeplot is rather low?

Sorry for asking so many questions. I just want to make sure I understand the results correctly.
I really like smudgeplot! It is super helpful and I am happy I came across this tool!

Thanks,
J.
