### ISSUE TITLE
Changing color  of letter(AB, AAB etc)

### ISSUE THREAD

**Issue by sefayten** [tbenavi1/sibling_kmers#93]
Hello, 
Thank you for this program. I generated smudgeplot; the only think I would like to change color of letter (AB, AAB etc) that written in the density area. I tried to check script but I could't do that. How can I do?
Thank you,
Sefa

**Comment by KamilSJaron** [comment]
Hi Sefa, these are the lines that are annotating the peaks in the picture: https://github.com/KamilSJaron/smudgeplot/blob/master/R/plot_expected_haplotype_structure.R#L15-L17

It's part of the package so if you modify this section you need to reinstall the package for changes to take place. Alternativelly, you can commend the line in the master script (https://github.com/KamilSJaron/smudgeplot/blob/master/exec/smudgeplot_plot.R#L189) and replace it with some sort of alternative function to annotate smudgeplot peaks.

Hope this helps
